name: sphinx-autogenerator

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events for the "main" branch
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Build documentation and commit
              run: |
                  git pull origin main
                  cd docs/
                  sudo apt-get install python3-sphinx
                  sudo rm code.rst
                  sudo rm modules.rst
                  sphinx-apidoc -o . ../src/
                  make html
                  cd ..
                  git config --global user.name "qureshi-ali"
                  git config --global user.email "qureshi.ali@outlook.com"
                  git add .
                  git commit -m "Updated documentation" -a || true
                  git push
